include: _default_template_yaml
task: extrapolation_bench_tomato_count_simulated
dataset_name: TOMATO_count_simulated
test_split: val
lmms_eval_specific_kwargs:
  default:
    post_prompt: "Only give the best option.\n"
