include: _default_template_yaml
task: direction_testbed_ablation_2H
dataset_name: 2way_horizontal
test_split: val
lmms_eval_specific_kwargs:
  default:
    post_prompt: "Only give the best option.\n"
