task: vlm_direction_testbed_E2E_shape_color
dataset_name: E2E_shape_color
include: default.yaml
test_split: val
doc_to_visual: !function utils.doc_to_visual
doc_to_text: !function utils.close_ended_doc_to_text
doc_to_target: "answer"
process_results: !function utils.process_results
metric_list:
  - metric: accuracy
    aggregation: !function utils.E2E_shape_color_aggregate
    higher_is_better: true
