task: ssv2_colored_edge_observe_full
dataset_name: ssv2_Colored_edge
include: default.yaml
test_split: val
doc_to_visual: !function utils.doc_to_visual
doc_to_text: !function utils.close_ended_doc_to_text
doc_to_target: "answer"
process_results: !function utils.colored_edge_process_results
metric_list:
  - metric: accuracy
    aggregation: !function utils.colored_edge_aggregate
    higher_is_better: true

lmms_eval_specific_kwargs:
  prompt_style: "ssv2_colored_edge_observe_full"

generation_kwargs:
  max_new_tokens: 512