task: ssv2_vp_default_lr
dataset_name: ssv2_VP_default
include: default.yaml
test_split: val
doc_to_visual: !function utils.doc_to_visual
doc_to_text: !function utils.close_ended_doc_to_text
doc_to_target: "answer"
process_results: !function utils.default_process_results
metric_list:
  - metric: accuracy
    aggregation: !function utils.default_aggregate
    higher_is_better: true