task: identity_testbed_synobj_synbg
dataset_name: synobj_synbg
include: default.yaml
test_split: val
doc_to_visual: !function utils.doc_to_visual
doc_to_text: !function utils.close_ended_doc_to_text
doc_to_target: "answer"
process_results: !function utils.process_results
metric_list:
  - metric: accuracy
    aggregation: !function utils.synobj_synbg_aggregate
    higher_is_better: true
